#!/usr/bin/env python3
"""
AI City Challenge 2026 - Track 6 (Cross-City Object Detection)
Trainer-package entrypoint for the Hafnia Training-as-a-Service platform
(Milestone Systems).

CONFIRMED PLATFORM FACTS (from public `hafnia` PyPI package / GitHub org
`milestone-hafnia`, and https://hafnia.readme.io/docs — see README.md for
full source list):
  - Trainer packages are plain Docker + Python, laid out as:
        Dockerfile, pyproject.toml, uv.lock, .python-version, .hafniaignore
        scripts/train.py + scripts/train.schema.json   <- this file + its
                                                            paired arg schema
        scripts/benchmark.py + scripts/benchmark.schema.json
        scripts/export_onnx.py
        src/, tests/
  - Dataset access inside a Hafnia job is via the `hafnia` Python SDK:
        from hafnia.dataset import HafniaDataset
        ds = HafniaDataset.from_name("<dataset-name>", version="<ver>")
    The SAME call transparently returns the small local sample dataset
    when run on a laptop (after `hafnia dataset download <name>`) and the
    full hidden dataset when the identical code is executed inside a
    managed Training-aaS job -- there is no separate "figure out the
    mount path" step, which was the single biggest unknown before this
    was confirmed.
  - `scripts/train.schema.json` is normally AUTO-GENERATED by the `hafnia`
    CLI from this script's argparse/click definitions and drives the
    Hafnia web dashboard's "Create Experiment" form. We ship a hand-written
    placeholder (see scripts/train.schema.json) that should be regenerated
    with `hafnia trainer create-zip` once logged in.

STILL UNCONFIRMED (requires Hafnia login — see README.md "Remaining
steps"):
  - The exact CLI name of the Track 6 sample/hidden dataset (placeholder
    below: TRACK6_DATASET_NAME, override via env var once known).
  - Whether train.py must expose a specific `--output-path` convention
    consumed by `hafnia experiment` result collection, beyond what
    HafniaLogger already handles.

MODEL CHOICE
------------
Hafnia's own reference example (`milestone-hafnia/trainer-object-detection`
on GitHub, public) wraps RF-DETR (Roboflow), not YOLO. We deliberately keep
Ultralytics YOLO11 as our baseline instead because:
  - It is a single pip package with a very stable, simple train() API,
    minimizing risk of the trainer package breaking inside Hafnia's
    container for reasons unrelated to modeling (dependency conflicts,
    RF-DETR's own train loop assumptions, etc).
  - Strong small/medium object performance, relevant for motorcycles,
    bicycles, and distant vehicles in cross-city traffic-camera footage.
  - Trivial to swap to RT-DETR (`--arch rtdetr-l.pt`, also shipped by
    ultralytics with the same API) if fine-grained truck/van/pickup
    confusion needs a transformer's larger receptive field.
Since Hafnia trainer packages are "bring your own Docker + Python", using
a non-reference framework is allowed -- just keep the entrypoint contract
(argparse flags <-> train.schema.json) consistent so the dashboard can
still drive it. If Hafnia's actual harness turns out to *require* the
RF-DETR skeleton specifically, see the note in README.md and adapt this
file to their `scripts/train.py` shape (should be a light rewrite, not a
redesign, since the imbalance/augmentation logic in src/ is
framework-agnostic where possible).
"""
import argparse
import os
import sys
import json
from pathlib import Path

import yaml

TRACK6_DATASET_NAME = os.environ.get("TRACK6_DATASET_NAME", "eccv-cross-city")
TRACK6_DATASET_VERSION = os.environ.get("TRACK6_DATASET_VERSION", "1.0.0")

# hafnia's experiment logger uses mlflow; mlflow >= 3.x refuses its default
# file-store backend unless this is set. Harmless when a real tracking
# backend is configured (the env var is only consulted for file stores).
os.environ.setdefault("MLFLOW_ALLOW_FILE_STORE", "true")


def parse_args():
    p = argparse.ArgumentParser(description="Track6 cross-city detector fine-tuning")
    p.add_argument("--dataset-name", type=str, default=TRACK6_DATASET_NAME,
                    help="Name passed to hafnia.dataset.HafniaDataset.from_name(). "
                         "CONFIRM the real Track 6 dataset identifier after login "
                         "(hafnia dataset ls) and update TRACK6_DATASET_NAME.")
    p.add_argument("--dataset-version", type=str, default=TRACK6_DATASET_VERSION)
    p.add_argument("--local-yolo-yaml", type=str, default=None,
                    help="Fallback: path to an Ultralytics-format data.yaml (see "
                         "../data.yaml) for fully-offline dry runs BEFORE the hafnia "
                         "SDK / sample dataset is available, e.g. against a hand-made "
                         "toy dataset. Ignored once --dataset-name resolves via the SDK.")
    p.add_argument("--arch", type=str, default="yolo11m.pt",
                    choices=["yolo11n.pt", "yolo11s.pt", "yolo11m.pt", "yolo11l.pt", "yolo11x.pt",
                             "rtdetr-l.pt", "rtdetr-x.pt"],
                    help="Pretrained checkpoint to fine-tune from (COCO-pretrained). "
                         "'m' recommended as the first real Hafnia run given the fixed "
                         "30,000-credit budget (Lite tier T4 = 83 credits/hr -> keep the "
                         "first few runs cheap and short to validate the pipeline, then "
                         "spend the bulk of the budget on the final longer run).")
    p.add_argument("--epochs", type=int, default=100)
    p.add_argument("--imgsz", type=int, default=960,
                    help="Traffic-cam frames often contain small/far objects (motorcycle, "
                         "bicycle, person) -> train above the default 640 if credits allow.")
    p.add_argument("--batch", type=int, default=-1, help="-1 = Ultralytics auto-batch")
    p.add_argument("--device", type=str, default=os.environ.get("HAFNIA_DEVICE", "0"))
    p.add_argument("--workers", type=int, default=4)  # Lite tier has 4 vCPUs
    p.add_argument("--output-path", type=str,
                    default=os.environ.get("HAFNIA_OUTPUT_PATH", "runs"),
                    help="Root output dir for weights/logs. Hafnia's result-collection "
                         "convention should be reconfirmed via HafniaLogger once logged in; "
                         "this default is safe for local/dry-run use regardless.")
    p.add_argument("--name", type=str, default="track6_run")
    p.add_argument("--resume", action="store_true")
    p.add_argument("--seed", type=int, default=0)

    # --- class-imbalance / fine-grained-confusion handling ---
    p.add_argument("--class-weighted-sampling", action="store_true", default=True,
                    help="Oversample images containing rare classes (Trailer, Heavy Duty "
                         "Vehicle, Combo Truck, Bicycle typically rarest in traffic footage). "
                         "See src/class_balance.py.")
    p.add_argument("--fl-gamma", type=float, default=1.5,
                    help="Focal-loss gamma applied to the classification branch via "
                         "src/focal_patch.py (0 = plain BCE). Helps separate visually-"
                         "similar classes: Pickup Truck vs Van vs Vehicle.Car, Single "
                         "Truck vs Combo Truck vs Heavy Duty Vehicle.")
    p.add_argument("--copy-paste", type=float, default=0.3,
                    help="Copy-paste augmentation probability; synthesizes extra instances "
                         "of rare classes onto other backgrounds. Uses only in-dataset crops "
                         "so it does not violate the 'no external data' rule.")
    p.add_argument("--mixup", type=float, default=0.15)
    p.add_argument("--close-mosaic", type=int, default=10,
                    help="Disable mosaic for the last N epochs to sharpen fine-grained "
                         "boundary localization before eval.")

    p.add_argument("--dry-run", action="store_true",
                    help="Sanity-check the pipeline (tiny model, 1 epoch, no real dataset "
                         "needed if --local-yolo-yaml points at a toy set) without spending "
                         "Hafnia credits. Run this as the FIRST-ever Hafnia submission to "
                         "validate the trainer package mechanics before any real training.")
    return p.parse_args()


def load_dataset_as_yolo_yaml(args) -> str:
    """Resolve the training data into an Ultralytics-format data.yaml path.

    Preferred path: hafnia SDK (works both for the local sample dataset and,
    unmodified, for the full hidden dataset once this code runs inside a
    real Hafnia Training-aaS job). Falls back to a hand-provided local yaml
    for fully offline scaffolding/dry-runs.
    """
    if args.local_yolo_yaml:
        print(f"[train.py] using local dataset yaml: {args.local_yolo_yaml}", file=sys.stderr)
        return args.local_yolo_yaml

    try:
        # SDK >= 0.7.14 moved HafniaDataset into a submodule; older docs used
        # `from hafnia.dataset import HafniaDataset`. Support both.
        try:
            from hafnia.dataset.hafnia_dataset import HafniaDataset
        except ImportError:
            from hafnia.dataset import HafniaDataset
    except ImportError:
        print("[train.py] hafnia SDK not importable and no --local-yolo-yaml given. "
              "Install `hafnia` (pip install hafnia) and run `hafnia configure` + "
              "`hafnia dataset download <name>` first, or pass --local-yolo-yaml for "
              "an offline dry run.", file=sys.stderr)
        raise

    import yaml

    from hafnia.utils import get_dataset_path_in_hafnia_cloud, is_hafnia_cloud_job

    if is_hafnia_cloud_job():
        # Inside a Hafnia job (or `hafnia runc launch-local`) the dataset is
        # already mounted; from_name would need platform credentials that
        # don't exist in the container.
        mount = Path(get_dataset_path_in_hafnia_cloud())
        print(f"[train.py] HAFNIA_CLOUD=true, using mounted dataset at {mount}", file=sys.stderr)
    else:
        HafniaDataset.from_name(args.dataset_name, version=args.dataset_version)  # ensures download
        from hafnia.utils import PATH_DATASETS
        mount = Path(PATH_DATASETS) / args.dataset_name

    # Zero-copy conversion straight from annotations.jsonl: symlink images and
    # write YOLO label txts only. The SDK's to_yolo_format() re-encodes a full
    # copy of every image, which doubles ~70GB on the full dataset and
    # exhausted the Lite instance's disk mid-run (shakeout v3, 67 min in).
    ann_path = mount / "annotations.jsonl"
    records = [json.loads(l) for l in ann_path.read_text().splitlines() if l.strip()]

    class_names = {}
    for r in records:
        for b in (r.get("bboxes") or []):
            if b.get("class_name") is not None and b.get("class_idx") is not None:
                class_names[int(b["class_idx"])] = b["class_name"]
    nc = max(class_names) + 1 if class_names else 0

    yolo_root = (Path(args.output_path) / "hafnia_dataset_yolo").resolve()
    split_txt = {}
    counts = {}
    for r in records:
        split = r["split"]
        img_src = (mount / r["file_path"]).resolve()
        split_dir = yolo_root / split
        img_dir = split_dir / "images"
        lbl_dir = split_dir / "labels"
        img_dir.mkdir(parents=True, exist_ok=True)
        lbl_dir.mkdir(parents=True, exist_ok=True)

        img_link = img_dir / img_src.name
        if not img_link.exists():
            img_link.symlink_to(img_src)

        lines = []
        for b in (r.get("bboxes") or []):
            cx = b["top_left_x"] + b["width"] / 2.0
            cy = b["top_left_y"] + b["height"] / 2.0
            lines.append(f'{int(b["class_idx"])} {cx:.6f} {cy:.6f} {b["width"]:.6f} {b["height"]:.6f}')
        (lbl_dir / (img_link.stem + ".txt")).write_text("\n".join(lines))

        split_txt.setdefault(split, []).append(str(img_link))
        counts[split] = counts.get(split, 0) + 1

    txt_paths = {}
    for split, paths in split_txt.items():
        p = yolo_root / f"{split}_images.txt"
        p.write_text("\n".join(paths))
        txt_paths[split] = str(p)

    train_txt = txt_paths.get("train") or next(iter(txt_paths.values()))
    val_txt = txt_paths.get("validation") or txt_paths.get("val") or txt_paths.get("test") or train_txt

    data_yaml = {
        "path": str(yolo_root),
        "train": train_txt,
        "val": val_txt,
        "nc": nc,
        "names": {i: class_names.get(i, f"class_{i}") for i in range(nc)},
    }
    data_yaml_path = yolo_root / "dataset.yaml"
    data_yaml_path.write_text(yaml.safe_dump(data_yaml))
    print(f"[train.py] zero-copy YOLO conversion: splits {counts}, {nc} classes -> {data_yaml_path}",
          file=sys.stderr)
    return str(data_yaml_path)


def main():
    args = parse_args()

    from ultralytics import YOLO
    from src.class_balance import maybe_reweight_dataset
    from src.focal_patch import apply_focal_loss

    data_yaml = load_dataset_as_yolo_yaml(args)

    if args.class_weighted_sampling:
        data_yaml = maybe_reweight_dataset(data_yaml)

    arch = "yolo11n.pt" if args.dry_run else args.arch
    epochs = 1 if args.dry_run else args.epochs

    model = YOLO(arch)

    if args.fl_gamma > 0:
        apply_focal_loss(model, gamma=args.fl_gamma)

    results = model.train(
        data=data_yaml,
        epochs=epochs,
        imgsz=args.imgsz,
        batch=args.batch,
        device=args.device,
        workers=args.workers,
        project=args.output_path,
        name=args.name,
        resume=args.resume,
        seed=args.seed,
        copy_paste=args.copy_paste,
        mixup=args.mixup,
        close_mosaic=args.close_mosaic,
        patience=30,
        val=True,
        plots=True,
        exist_ok=True,
    )

    # Consolidate artifacts. TODO once logged in: check whether Hafnia's
    # HafniaLogger (github.com/milestone-hafnia/hafnia) should be used
    # instead of/alongside this plain-json summary for metrics to surface
    # correctly on the platform's experiment dashboard.
    run_dir = Path(args.output_path) / args.name
    best_pt = run_dir / "weights" / "best.pt"
    summary = {
        "arch": arch,
        "epochs": epochs,
        "imgsz": args.imgsz,
        "best_weights": str(best_pt),
        "metrics": getattr(results, "results_dict", {}),
    }
    with open(run_dir / "hafnia_summary.json", "w") as f:
        json.dump(summary, f, indent=2, default=str)
    print(f"[train.py] done. best weights: {best_pt}")


if __name__ == "__main__":
    main()
